// Estados del proceso de Step Functions
export const PROCESS_STATES = {
  IDLE: 'idle',
  RUNNING: 'RUNNING',
  INITIALIZING: 'INITIALIZING',
  SEPARATING_CLIENTS: 'SEPARATING_CLIENTS',
  PROCESSING_SINGLE: 'PROCESSING_SINGLE',
  PROCESSING_MULTI: 'PROCESSING_MULTI',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  AGGREGATING: 'AGGREGATING',
  CHECKING: 'CHECKING',
  CHECKED: 'CHECKED',
  DOWNLOADING: 'DOWNLOADING',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_WARNINGS: 'COMPLETED_WITH_WARNINGS',
  FAILED: 'FAILED'
};

// Mapeo de progreso por estado
export const PROGRESS_MAP = {
  [PROCESS_STATES.RUNNING]: 5,
  [PROCESS_STATES.INITIALIZING]: 10,
  [PROCESS_STATES.SEPARATING_CLIENTS]: 15,
  [PROCESS_STATES.PROCESSING_SINGLE]: 40,
  [PROCESS_STATES.PROCESSING_MULTI]: 25,
  [PROCESS_STATES.PROCESSING]: 40,
  [PROCESS_STATES.PROCESSED]: 60,
  [PROCESS_STATES.AGGREGATING]: 70,
  [PROCESS_STATES.CHECKING]: 80,
  [PROCESS_STATES.CHECKED]: 90,
  [PROCESS_STATES.DOWNLOADING]: 95,
  [PROCESS_STATES.COMPLETED]: 100,
  [PROCESS_STATES.COMPLETED_WITH_WARNINGS]: 100
};

// Estados que indican finalización
export const FINISHED_STATES = [
  PROCESS_STATES.COMPLETED,
  PROCESS_STATES.COMPLETED_WITH_WARNINGS,
  PROCESS_STATES.PROCESSED,
  PROCESS_STATES.FAILED
];

// Estados que indican éxito
export const SUCCESS_STATES = [
  PROCESS_STATES.COMPLETED,
  PROCESS_STATES.COMPLETED_WITH_WARNINGS,
  PROCESS_STATES.PROCESSED
];
