Resources:
  # Rol para que API Gateway escriba logs a CloudWatch
  # Nombre dinámico por ambiente para evitar conflictos
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: serverlessApiGatewayCloudWatchRole-${self:provider.stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      # Tags removidos - Serverless Framework los agrega automáticamente desde provider.tags

