Resources:
  # Rol para que API Gateway escriba logs a CloudWatch
  # Nombre estático (compartido entre ambientes en la misma cuenta AWS)
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: serverlessApiGatewayCloudWatchRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      # Tags removidos - Serverless Framework los agrega automáticamente desde provider.tags

