Resources:
  # Bucket para almacenar logs de acceso S3
  S3LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-s3-logs
      # Removido AccessControl para compatibilidad con BucketOwnerEnforced
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      # Removido LoggingConfiguration para evitar referencia circular
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
      # Tags removidos - Serverless Framework los agrega automáticamente desde provider.tags

  UploadsBucket:
    Type: AWS::S3::Bucket
    DependsOn: S3LogsBucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-uploads
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogsBucket
        LogFilePrefix: uploads-access-logs/
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldUploads
            Status: Enabled
            ExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Tags removidos - Serverless Framework los agrega automáticamente desde provider.tags

  ResultsBucket:
    Type: AWS::S3::Bucket
    DependsOn: S3LogsBucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-results
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogsBucket
        LogFilePrefix: results-access-logs/
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldResults
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Tags removidos - Serverless Framework los agrega automáticamente desde provider.tags

  # Política para permitir que S3 escriba logs en el bucket
  S3LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: S3LogsBucket
    Properties:
      Bucket: !Ref S3LogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub "${S3LogsBucket.Arn}/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
